### Create a user
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
    "username": "nesc",
    "email": "",
    "password": ""
}


### Sign up or sign in a user with google
POST http://localhost:3000/api/auth/google
Content-Type: application/json

{
    "username": "user10",
    "email": "user10@example.com"
}


### Sign in a user
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
    "email": "jose@example.com",
    "password": "jose"
}